#!/usr/bin/env php
<?php

// installed via composer?

use Bitban\PhpCodeQualityTools\Console\Application;

if (file_exists($a = __DIR__ . '/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

set_time_limit(0);

$app = (new Application())->run();
