#!/usr/bin/env php
<?php

// installed via composer?

use Bitban\PhpCodeQualityTools\Console\Application;
use Bitban\PhpCodeQualityTools\Infrastructure\Project;

if (file_exists($a = __DIR__ . '/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

set_time_limit(0);

$configurationFile = (new Project())->getBasepath() . '/' . Application::PROJECT_CONF_FILENAME;
$app = (new Application())
    ->loadConfiguration($configurationFile)
    ->run();
